version: '3.4'
services:
  kibana6:
    image: docker.elastic.co/kibana/kibana:6.1.4
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch6

  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

