version: '3.4'

services:

  restairline.api:
    image: restairline:${TAG:-latest}
    build:
      args:
        Version: "1"
      context: ../src
      dockerfile: ./RestAirline.Api/Dockerfile
    depends_on:
      - mssql.data
      - mongodb.data
    container_name: restairline_api

  mssql.data:
    image: microsoft/mssql-server-linux:2017-latest
    
  mongodb.data:
    image: mongo:4.0
    
    
